FirstName = input("What is your first name? ")
LastName = input("What is your last name? ")
Location = input("What is your location? ")
Age = input("What is your age? ")
print("Hi "+ FirstName + " " + LastName + " ! Your loacation is " + Location + " and you are " + Age + " years ald.")